# Generated by Django 3.2 on 2021-04-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='f_date_ev',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='event',
            name='f_time_ev',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время'),
        ),
    ]
