# Generated by Django 3.2 on 2021-04-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210416_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_unic_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Уникалныйидендификатор')),
                ('f_identifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='идентификатор')),
                ('f_name_resource', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ресурс контроллера')),
                ('f_name_ev', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование события')),
                ('f_name_obj', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя обьекта')),
                ('f_name_subdiv', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование подразделения, если событие связано с сотрудником')),
                ('f_name_appoint', models.CharField(blank=True, max_length=255, null=True, verbose_name='наименование должности, если событие связано с сотрудником')),
                ('f_date_ev', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата')),
                ('f_time_ev', models.CharField(blank=True, max_length=255, null=True, verbose_name='Время')),
            ],
        ),
        migrations.RenameModel(
            old_name='Event',
            new_name='EventUser',
        ),
    ]
