# Generated by Django 3.2 on 2021-04-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Уникалный id')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('bin', models.CharField(blank=True, max_length=255, null=True, verbose_name='БИН')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
