# Generated by Django 3.2 on 2021-04-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20210419_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='name',
            new_name='displayname',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='unit_id',
            new_name='id_internal',
        ),
        migrations.AddField(
            model_name='unit',
            name='id_parent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Уникалный id парента'),
        ),
    ]
