# Generated by Django 3.2 on 2021-04-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20210419_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventuser',
            name='f_name_appoint',
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='f_name_obj',
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='f_name_resource',
        ),
        migrations.AddField(
            model_name='eventuser',
            name='bin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бин'),
        ),
        migrations.AddField(
            model_name='eventuser',
            name='f_areas_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вход/Выход'),
        ),
        migrations.AddField(
            model_name='eventuser',
            name='f_subdiv_id_internal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Id подразделения, если событие связано с сотрудником'),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='f_unic_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Уникальный идендификатор'),
        ),
    ]
