# Generated by Django 3.2 on 2021-06-01 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_testdb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventuser',
            options={'ordering': ['f_name_ev'], 'verbose_name': 'Событие', 'verbose_name_plural': 'Событий'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['displayname'], 'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделений'},
        ),
    ]
