# Generated by Django 3.2 on 2021-06-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20210628_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventuser',
            name='bin',
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='f_name_subdiv',
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='f_subdiv_id_internal',
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='f_unic_id',
        ),
    ]
