# Generated by Django 3.2 on 2021-06-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20210628_1101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventGuest',
        ),
        migrations.DeleteModel(
            name='TestDB',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.AddField(
            model_name='eventuser',
            name='f_unic_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ii'),
        ),
    ]
